# Generated by Django 4.1.4 on 2022-12-11 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 11, 47, 27, 351692)),
        ),
    ]
