# Generated by Django 4.1.4 on 2022-12-12 10:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
